import Layout from "./components/layout";
import "./globals.css";
import { Montserrat } from "next/font/google";

const monsterrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{backgroundColor: 'white !important'}} className={...monsterrat.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
